# Generated by Django 4.2.9 on 2024-03-14 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default=None, max_length=50, verbose_name='授课科目'),
        ),
    ]
