# Generated by Django 4.2.9 on 2024-03-14 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='name',
        ),
        migrations.AddField(
            model_name='class',
            name='grade',
            field=models.CharField(choices=[('1', '1班'), ('2', '2班'), ('3', '3班'), ('4', '4班'), ('5', '5班'), ('6', '6班')], default=None, max_length=1, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='class',
            name='year',
            field=models.CharField(choices=[('2020', '2020级'), ('2021', '2021级'), ('2022', '2022级')], default=None, max_length=4, verbose_name='年级'),
        ),
    ]
