# Generated by Django 4.2.9 on 2024-03-14 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_class_name_class_grade_class_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='class',
            name='year',
        ),
        migrations.AddField(
            model_name='class',
            name='name',
            field=models.CharField(choices=[('2020级1班', '2020级1班'), ('2020级2班', '2020级2班'), ('2020级3班', '2020级3班'), ('2020级4班', '2020级4班'), ('2020级5班', '2020级5班'), ('2020级6班', '2020级6班'), ('2021级1班', '2021级1班'), ('2021级2班', '2021级2班'), ('2021级3班', '2021级3班'), ('2021级4班', '2021级4班'), ('2021级5班', '2021级5班'), ('2021级6班', '2021级6班'), ('2022级1班', '2022级1班'), ('2022级2班', '2022级2班'), ('2022级3班', '2022级3班'), ('2022级4班', '2022级4班'), ('2022级5班', '2022级5班'), ('2022级6班', '2022级6班')], default=None, max_length=10, verbose_name='班级名称'),
        ),
    ]
