# Generated by Django 4.2.9 on 2024-03-18 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_submittedevaluation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submittedevaluation',
            name='submission_date',
        ),
        migrations.AddField(
            model_name='submittedevaluation',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='日期'),
        ),
    ]
