# Generated by Django 4.2.9 on 2024-03-24 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_groupmessage_directmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupmessage',
            name='group_name',
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='class_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='web.class'),
        ),
    ]
