# Generated by Django 4.2.9 on 2024-03-26 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_remove_groupmessage_group_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='directmessage',
            name='emojis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='directmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='direct_message_images/'),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='emojis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='groupmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='group_message_images/'),
        ),
    ]
