# Generated by Django 4.2.9 on 2024-03-28 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0016_homework'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='remark',
            field=models.FileField(blank=True, null=True, upload_to='homework_attachments/'),
        ),
    ]
