# Generated by Django 4.2.9 on 2024-03-29 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_submission_studenthomework'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studenthomework',
            name='submission',
        ),
        migrations.AddField(
            model_name='submission',
            name='student_homework',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='web.studenthomework'),
        ),
    ]
