# Generated by Django 4.2.9 on 2024-03-30 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_remove_studenthomework_submission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='approval_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='grading',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
    ]
