# Generated by Django 4.2.9 on 2024-03-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_submission_approval_comment_submission_grading'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='holiday_images/')),
            ],
        ),
    ]
