# Generated by Django 4.2.9 on 2024-03-31 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_classschedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='grade',
            field=models.CharField(choices=[('1', '1班'), ('2', '2班'), ('3', '3班'), ('4', '4班'), ('5', '5班'), ('6', '6班'), ('7', '7班'), ('8', '8班')], default=None, max_length=1, verbose_name='班级'),
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('approved', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('未批假', '未批假'), ('假期中', '假期中'), ('已销假', '已销假'), ('到时间未销假', '到时间未销假')], default='未批假', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.student')),
            ],
        ),
    ]
